import { Project } from "@/models/project";

export const paginatedProjects: { [key: string]: { [key: number]: Project[] } } = {
  ar: {
    1: [
      {
        id: "7d09d81a-5235-4dc9-be26-d43d9aa3c3f8",
        name: "تطوير المتنزة الوطني السابع والثامن (المجموعة الثانية - المرحلة الثانية)",
        status: "late",
        percentage: 0,
        consultant: "مكتب الإبداع العربي للإستشارات الهندسية",
        contractor: "شركة ظل النخيل للمقاولات شركة شخص واحد",
        department: "الإدارة العامة للمتنزهات الوطنية",
        owner: "المركز الوطني لتنمية الغطاء النباتي ومكافحة التصحر",
        studyEntity: "جهة دراسة عامة",
        type: "مبادرات | الإنشاء والتنفيذ",
      },
      {
        id: "b9292206-ab8f-4a0b-aee9-8f59e9ed49be",
        name: "إنشاء المتنزة السادس (السبخة) (المجموعة الأولى - المرحلة الثانية)",
        status: "onSchedule",
        percentage: 0,
        consultant: "مكتب الإبداع العربي للإستشارات الهندسية",
        contractor: "شركة ظل النخيل للمقاولات شركة شخص واحد",
        department: "الإدارة العامة للمتنزهات الوطنية",
        owner: "المركز الوطني لتنمية الغطاء النباتي ومكافحة التصحر",
        studyEntity: "جهة دراسة عامة",
        type: "مبادرات | الإنشاء والتنفيذ",
      },
      {
        id: "cecbb029-074f-4760-8c6c-d92dd0a8eaa0",
        name: "ترميم وتأهيل متنزة الإحساء الوطني بمحافظة الإحساء بمنطقة الشرقية",
        status: "late",
        percentage: 0,
        consultant: "مكتب الإبداع العربي للإستشارات الهندسية",
        contractor: "شركة ظل النخيل للمقاولات شركة شخص واحد",
        department: "الإدارة العامة للمتنزهات الوطنية",
        owner: "المركز الوطني لتنمية الغطاء النباتي ومكافحة التصحر",
        studyEntity: "جهة دراسة عامة",
        type: "مبادرات | الإنشاء والتنفيذ",
      },
      {
        id: "36b953aa-22c5-48c9-82b8-8a31ad6d397c",
        name: "مشروع تشجير منتزه الاني البري بوادي حلي بمحافظة القنفذة المرحلة الاولى",
        status: "onSchedule",
        percentage: 61.72,
        consultant: "مكتب الإبداع العربي للإستشارات الهندسية",
        contractor: "شركة ظل النخيل للمقاولات شركة شخص واحد",
        department: "الإدارة العامة للمتنزهات الوطنية",
        owner: "المركز الوطني لتنمية الغطاء النباتي ومكافحة التصحر",
        studyEntity: "جهة دراسة عامة",
        type: "مبادرات | الإنشاء والتنفيذ",
      },
      {
        id: "f45f4b52-0777-4a1e-b313-2999ee4c3137",
        name: "تصميم منتزة الوطني التاسع والعاشر (المجموعة الثانية - المرحلة الثانية)",
        status: "stumbling",
        percentage: 20,
        consultant: "مكتب الإبداع العربي للإستشارات الهندسية",
        contractor: "شركة ظل النخيل للمقاولات شركة شخص واحد",
        department: "الإدارة العامة للمتنزهات الوطنية",
        owner: "المركز الوطني لتنمية الغطاء النباتي ومكافحة التصحر",
        studyEntity: "جهة دراسة عامة",
        type: "مبادرات | الإنشاء والتنفيذ",
      },
      {
        id: "d54de1e9-191a-4cf3-9a5e-4e13cb8c9e50",
        name: "تطوير المتنزة التاسع والعاشر (المجموعة الثانية - المرحلة الثانية)",
        status: "early",
        percentage: 5,
        consultant: "مكتب الإبداع العربي للإستشارات الهندسية",
        contractor: "شركة ظل النخيل للمقاولات شركة شخص واحد",
        department: "الإدارة العامة للمتنزهات الوطنية",
        owner: "المركز الوطني لتنمية الغطاء النباتي ومكافحة التصحر",
        studyEntity: "جهة دراسة عامة",
        type: "مبادرات | الإنشاء والتنفيذ",
      },
    ],
    2: [
      {
        id: "1ba8b4be-7c9c-413f-a35c-e8db86b84008",
        name: "تطوير المتنزة الوطني السابع والثامن (المجموعة الثانية - المرحلة الثانية)",
        status: "late",
        percentage: 0,
        consultant: "مكتب الإبداع العربي للإستشارات الهندسية",
        contractor: "شركة ظل النخيل للمقاولات شركة شخص واحد",
        department: "الإدارة العامة للمتنزهات الوطنية",
        owner: "المركز الوطني لتنمية الغطاء النباتي ومكافحة التصحر",
        studyEntity: "جهة دراسة عامة",
        type: "مبادرات | الإنشاء والتنفيذ",
      },
      {
        id: "c401a370-0745-4208-9a87-e1b819c1d9e4",
        name: "إنشاء المتنزة السادس (السبخة) (المجموعة الأولى - المرحلة الثانية)",
        status: "onSchedule",
        percentage: 0,
        consultant: "مكتب الإبداع العربي للإستشارات الهندسية",
        contractor: "شركة ظل النخيل للمقاولات شركة شخص واحد",
        department: "الإدارة العامة للمتنزهات الوطنية",
        owner: "المركز الوطني لتنمية الغطاء النباتي ومكافحة التصحر",
        studyEntity: "جهة دراسة عامة",
        type: "مبادرات | الإنشاء والتنفيذ",
      },
      {
        id: "c6f6489d-6b4b-4a93-a6ce-b1897b1f16e3",
        name: "ترميم وتأهيل متنزة الإحساء الوطني بمحافظة الإحساء بمنطقة الشرقية",
        status: "late",
        percentage: 0,
        consultant: "مكتب الإبداع العربي للإستشارات الهندسية",
        contractor: "شركة ظل النخيل للمقاولات شركة شخص واحد",
        department: "الإدارة العامة للمتنزهات الوطنية",
        owner: "المركز الوطني لتنمية الغطاء النباتي ومكافحة التصحر",
        studyEntity: "جهة دراسة عامة",
        type: "مبادرات | الإنشاء والتنفيذ",
      },
      {
        id: "bd5ab08c-d381-49c5-8bd7-68ec7c35a164",
        name: "مشروع تشجير منتزه الاني البري بوادي حلي بمحافظة القنفذة المرحلة الاولى",
        status: "onSchedule",
        percentage: 61.72,
        consultant: "مكتب الإبداع العربي للإستشارات الهندسية",
        contractor: "شركة ظل النخيل للمقاولات شركة شخص واحد",
        department: "الإدارة العامة للمتنزهات الوطنية",
        owner: "المركز الوطني لتنمية الغطاء النباتي ومكافحة التصحر",
        studyEntity: "جهة دراسة عامة",
        type: "مبادرات | الإنشاء والتنفيذ",
      },
      {
        id: "b345eb0b-f69f-4c69-8ec3-6480741cb882",
        name: "تصميم منتزة الوطني التاسع والعاشر (المجموعة الثانية - المرحلة الثانية)",
        status: "stumbling",
        percentage: 20,
        consultant: "مكتب الإبداع العربي للإستشارات الهندسية",
        contractor: "شركة ظل النخيل للمقاولات شركة شخص واحد",
        department: "الإدارة العامة للمتنزهات الوطنية",
        owner: "المركز الوطني لتنمية الغطاء النباتي ومكافحة التصحر",
        studyEntity: "جهة دراسة عامة",
        type: "مبادرات | الإنشاء والتنفيذ",
      },
      {
        id: "0835a771-a54a-4cc1-88a0-21fa1df3c50c",
        name: "تطوير المتنزة التاسع والعاشر (المجموعة الثانية - المرحلة الثانية)",
        status: "early",
        percentage: 5,
        consultant: "مكتب الإبداع العربي للإستشارات الهندسية",
        contractor: "شركة ظل النخيل للمقاولات شركة شخص واحد",
        department: "الإدارة العامة للمتنزهات الوطنية",
        owner: "المركز الوطني لتنمية الغطاء النباتي ومكافحة التصحر",
        studyEntity: "جهة دراسة عامة",
        type: "مبادرات | الإنشاء والتنفيذ",
      },
    ],
  },
  en: {
    1: [
      {
        id: "6c81d7ca-b967-40aa-8605-89d47f828bc8",
        name: "Development of the Seventh and Eighth National Park (Group Two - Phase Two)",
        status: "late",
        percentage: 0,
        consultant: "Arab Creativity Office for Engineering Consultations",
        contractor: "Palm Shadow Contracting Company is a one-person company.",
        department: "General Administration of National Parks",
        owner: "National Center for Vegetation Cover Development and Combating Desertification",
        studyEntity: "General Study Authority",
        type: "Initiatives | Creation and implementation",
      },
      {
        id: "abc3b9d6-6a01-48bb-8dfb-37ab339e02d1",
        name: "Establishment of the Sixth Park (Al-Sabkha) (Group One - Phase Two)",
        status: "onSchedule",
        percentage: 0,
        consultant: "Arab Creativity Office for Engineering Consultations",
        contractor: "Palm Shadow Contracting Company is a one-person company.",
        department: "General Administration of National Parks",
        owner: "National Center for Vegetation Cover Development and Combating Desertification",
        studyEntity: "General Study Authority",
        type: "Initiatives | Creation and implementation",
      },
      {
        id: "849bda85-2461-495c-b783-70708899a2b6",
        name: "Restoration and Rehabilitation of Al-Ahsa National Park in Al-Ahsa Governorate, Eastern Region",
        status: "late",
        percentage: 0,
        consultant: "Arab Creativity Office for Engineering Consultations",
        contractor: "Palm Shadow Contracting Company is a one-person company.",
        department: "General Administration of National Parks",
        owner: "National Center for Vegetation Cover Development and Combating Desertification",
        studyEntity: "General Study Authority",
        type: "Initiatives | Creation and implementation",
      },
      {
        id: "acffa595-21a4-427d-8464-e8f4d4e000f2",
        name: "Project for Afforestation of Al-Ani Wild Park in Wadi Hali, Al-Qunfudhah Governorate - Phase One",
        status: "onSchedule",
        percentage: 61.72,
        consultant: "Arab Creativity Office for Engineering Consultations",
        contractor: "Palm Shadow Contracting Company is a one-person company.",
        department: "General Administration of National Parks",
        owner: "National Center for Vegetation Cover Development and Combating Desertification",
        studyEntity: "General Study Authority",
        type: "Initiatives | Creation and implementation",
      },
      {
        id: "43b7bab4-eb6f-4d0c-8b05-be0808ae28c5",
        name: "Design of the Ninth and Tenth National Park (Group Two - Phase Two)",
        status: "stumbling",
        percentage: 20,
        consultant: "Arab Creativity Office for Engineering Consultations",
        contractor: "Palm Shadow Contracting Company is a one-person company.",
        department: "General Administration of National Parks",
        owner: "National Center for Vegetation Cover Development and Combating Desertification",
        studyEntity: "General Study Authority",
        type: "Initiatives | Creation and implementation",
      },
      {
        id: "3d0e2a46-01d5-4e10-aeb7-ea304503642f",
        name: "Development of the Ninth and Tenth National Park (Group Two - Phase Two)",
        status: "early",
        percentage: 5,
        consultant: "Arab Creativity Office for Engineering Consultations",
        contractor: "Palm Shadow Contracting Company is a one-person company.",
        department: "General Administration of National Parks",
        owner: "National Center for Vegetation Cover Development and Combating Desertification",
        studyEntity: "General Study Authority",
        type: "Initiatives | Creation and implementation",
      },
    ],
    2: [
      {
        id: "fc8f1124-9247-4a33-a8ad-a2fa53fc5a9c",
        name: "Development of the Seventh and Eighth National Park (Group Two - Phase Two)",
        status: "late",
        percentage: 0,
        consultant: "Arab Creativity Office for Engineering Consultations",
        contractor: "Palm Shadow Contracting Company is a one-person company.",
        department: "General Administration of National Parks",
        owner: "National Center for Vegetation Cover Development and Combating Desertification",
        studyEntity: "General Study Authority",
        type: "Initiatives | Creation and implementation",
      },
      {
        id: "19b889c7-9240-4338-8b2d-d34e6d36d9a6",
        name: "Establishment of the Sixth Park (Al-Sabkha) (Group One - Phase Two)",
        status: "onSchedule",
        percentage: 0,
        consultant: "Arab Creativity Office for Engineering Consultations",
        contractor: "Palm Shadow Contracting Company is a one-person company.",
        department: "General Administration of National Parks",
        owner: "National Center for Vegetation Cover Development and Combating Desertification",
        studyEntity: "General Study Authority",
        type: "Initiatives | Creation and implementation",
      },
      {
        id: "10a8b377-f436-4493-bcc8-c8c8970e5dfd",
        name: "Restoration and Rehabilitation of Al-Ahsa National Park in Al-Ahsa Governorate, Eastern Region",
        status: "late",
        percentage: 0,
        consultant: "Arab Creativity Office for Engineering Consultations",
        contractor: "Palm Shadow Contracting Company is a one-person company.",
        department: "General Administration of National Parks",
        owner: "National Center for Vegetation Cover Development and Combating Desertification",
        studyEntity: "General Study Authority",
        type: "Initiatives | Creation and implementation",
      },
      {
        id: "6dd6d65a-b7b2-4ec6-82b6-eb3c16304873",
        name: "Project for Afforestation of Al-Ani Wild Park in Wadi Hali, Al-Qunfudhah Governorate - Phase One",
        status: "onSchedule",
        percentage: 61.72,
        consultant: "Arab Creativity Office for Engineering Consultations",
        contractor: "Palm Shadow Contracting Company is a one-person company.",
        department: "General Administration of National Parks",
        owner: "National Center for Vegetation Cover Development and Combating Desertification",
        studyEntity: "General Study Authority",
        type: "Initiatives | Creation and implementation",
      },
      {
        id: "cd7e5749-a9fe-4d3f-8c47-1d411117b247",
        name: "Design of the Ninth and Tenth National Park (Group Two - Phase Two)",
        status: "stumbling",
        percentage: 20,
        consultant: "Arab Creativity Office for Engineering Consultations",
        contractor: "Palm Shadow Contracting Company is a one-person company.",
        department: "General Administration of National Parks",
        owner: "National Center for Vegetation Cover Development and Combating Desertification",
        studyEntity: "General Study Authority",
        type: "Initiatives | Creation and implementation",
      },
      {
        id: "01add901-f22a-45df-b619-17f33cc3e1c2",
        name: "Development of the Ninth and Tenth National Park (Group Two - Phase Two)",
        status: "early",
        percentage: 5,
        consultant: "Arab Creativity Office for Engineering Consultations",
        contractor: "Palm Shadow Contracting Company is a one-person company.",
        department: "General Administration of National Parks",
        owner: "National Center for Vegetation Cover Development and Combating Desertification",
        studyEntity: "General Study Authority",
        type: "Initiatives | Creation and implementation",
      },
    ],
  },
};
