import { Project } from "@/models/project";
import { v4 as uuidv4 } from "uuid";

export const paginatedProjects: { [key: string]: { [key: number]: Project[] } } = {
  ar: {
    1: [
      {
        id: uuidv4(),
        name: "تطوير المتنزة الوطني السابع والثامن (المجموعة الثانية - المرحلة الثانية)",
        status: "late",
        percentage: 0.0,
        consultant: "مكتب الإبداع العربي للإستشارات الهندسية",
        contractor: "شركة ظل النخيل للمقاولات شركة شخص واحد",
        department: "الإدارة العامة للمتنزهات الوطنية",
        owner: "المركز الوطني لتنمية الغطاء النباتي ومكافحة التصحر",
        studyEntity: "جهة دراسة عامة",
        type: "مبادرات | الإنشاء والتنفيذ",
      },
      {
        id: uuidv4(),
        name: "إنشاء المتنزة السادس (السبخة) (المجموعة الأولى - المرحلة الثانية)",
        status: "onSchedule",
        percentage: 0.0,
        consultant: "مكتب الإبداع العربي للإستشارات الهندسية",
        contractor: "شركة ظل النخيل للمقاولات شركة شخص واحد",
        department: "الإدارة العامة للمتنزهات الوطنية",
        owner: "المركز الوطني لتنمية الغطاء النباتي ومكافحة التصحر",
        studyEntity: "جهة دراسة عامة",
        type: "مبادرات | الإنشاء والتنفيذ",
      },
      {
        id: uuidv4(),
        name: "ترميم وتأهيل متنزة الإحساء الوطني بمحافظة الإحساء بمنطقة الشرقية",
        status: "late",
        percentage: 0.0,
        consultant: "مكتب الإبداع العربي للإستشارات الهندسية",
        contractor: "شركة ظل النخيل للمقاولات شركة شخص واحد",
        department: "الإدارة العامة للمتنزهات الوطنية",
        owner: "المركز الوطني لتنمية الغطاء النباتي ومكافحة التصحر",
        studyEntity: "جهة دراسة عامة",
        type: "مبادرات | الإنشاء والتنفيذ",
      },
      {
        id: uuidv4(),
        name: "مشروع تشجير منتزه الاني البري بوادي حلي بمحافظة القنفذة المرحلة الاولى",
        status: "onSchedule",
        percentage: 61.72,
        consultant: "مكتب الإبداع العربي للإستشارات الهندسية",
        contractor: "شركة ظل النخيل للمقاولات شركة شخص واحد",
        department: "الإدارة العامة للمتنزهات الوطنية",
        owner: "المركز الوطني لتنمية الغطاء النباتي ومكافحة التصحر",
        studyEntity: "جهة دراسة عامة",
        type: "مبادرات | الإنشاء والتنفيذ",
      },
      {
        id: uuidv4(),
        name: "تصميم منتزة الوطني التاسع والعاشر (المجموعة الثانية - المرحلة الثانية)",
        status: "stumbling",
        percentage: 20.0,
        consultant: "مكتب الإبداع العربي للإستشارات الهندسية",
        contractor: "شركة ظل النخيل للمقاولات شركة شخص واحد",
        department: "الإدارة العامة للمتنزهات الوطنية",
        owner: "المركز الوطني لتنمية الغطاء النباتي ومكافحة التصحر",
        studyEntity: "جهة دراسة عامة",
        type: "مبادرات | الإنشاء والتنفيذ",
      },
      {
        id: uuidv4(),
        name: "تطوير المتنزة التاسع والعاشر (المجموعة الثانية - المرحلة الثانية)",
        status: "early",
        percentage: 5.0,
        consultant: "مكتب الإبداع العربي للإستشارات الهندسية",
        contractor: "شركة ظل النخيل للمقاولات شركة شخص واحد",
        department: "الإدارة العامة للمتنزهات الوطنية",
        owner: "المركز الوطني لتنمية الغطاء النباتي ومكافحة التصحر",
        studyEntity: "جهة دراسة عامة",
        type: "مبادرات | الإنشاء والتنفيذ",
      },
    ],
    2: [
      {
        id: uuidv4(),
        name: "تطوير المتنزة الوطني السابع والثامن (المجموعة الثانية - المرحلة الثانية)",
        status: "late",
        percentage: 0.0,
        consultant: "مكتب الإبداع العربي للإستشارات الهندسية",
        contractor: "شركة ظل النخيل للمقاولات شركة شخص واحد",
        department: "الإدارة العامة للمتنزهات الوطنية",
        owner: "المركز الوطني لتنمية الغطاء النباتي ومكافحة التصحر",
        studyEntity: "جهة دراسة عامة",
        type: "مبادرات | الإنشاء والتنفيذ",
      },
      {
        id: uuidv4(),
        name: "إنشاء المتنزة السادس (السبخة) (المجموعة الأولى - المرحلة الثانية)",
        status: "onSchedule",
        percentage: 0.0,
        consultant: "مكتب الإبداع العربي للإستشارات الهندسية",
        contractor: "شركة ظل النخيل للمقاولات شركة شخص واحد",
        department: "الإدارة العامة للمتنزهات الوطنية",
        owner: "المركز الوطني لتنمية الغطاء النباتي ومكافحة التصحر",
        studyEntity: "جهة دراسة عامة",
        type: "مبادرات | الإنشاء والتنفيذ",
      },
      {
        id: uuidv4(),
        name: "ترميم وتأهيل متنزة الإحساء الوطني بمحافظة الإحساء بمنطقة الشرقية",
        status: "late",
        percentage: 0.0,
        consultant: "مكتب الإبداع العربي للإستشارات الهندسية",
        contractor: "شركة ظل النخيل للمقاولات شركة شخص واحد",
        department: "الإدارة العامة للمتنزهات الوطنية",
        owner: "المركز الوطني لتنمية الغطاء النباتي ومكافحة التصحر",
        studyEntity: "جهة دراسة عامة",
        type: "مبادرات | الإنشاء والتنفيذ",
      },
      {
        id: uuidv4(),
        name: "مشروع تشجير منتزه الاني البري بوادي حلي بمحافظة القنفذة المرحلة الاولى",
        status: "onSchedule",
        percentage: 61.72,
        consultant: "مكتب الإبداع العربي للإستشارات الهندسية",
        contractor: "شركة ظل النخيل للمقاولات شركة شخص واحد",
        department: "الإدارة العامة للمتنزهات الوطنية",
        owner: "المركز الوطني لتنمية الغطاء النباتي ومكافحة التصحر",
        studyEntity: "جهة دراسة عامة",
        type: "مبادرات | الإنشاء والتنفيذ",
      },
      {
        id: uuidv4(),
        name: "تصميم منتزة الوطني التاسع والعاشر (المجموعة الثانية - المرحلة الثانية)",
        status: "stumbling",
        percentage: 20.0,
        consultant: "مكتب الإبداع العربي للإستشارات الهندسية",
        contractor: "شركة ظل النخيل للمقاولات شركة شخص واحد",
        department: "الإدارة العامة للمتنزهات الوطنية",
        owner: "المركز الوطني لتنمية الغطاء النباتي ومكافحة التصحر",
        studyEntity: "جهة دراسة عامة",
        type: "مبادرات | الإنشاء والتنفيذ",
      },
      {
        id: uuidv4(),
        name: "تطوير المتنزة التاسع والعاشر (المجموعة الثانية - المرحلة الثانية)",
        status: "early",
        percentage: 5.0,
        consultant: "مكتب الإبداع العربي للإستشارات الهندسية",
        contractor: "شركة ظل النخيل للمقاولات شركة شخص واحد",
        department: "الإدارة العامة للمتنزهات الوطنية",
        owner: "المركز الوطني لتنمية الغطاء النباتي ومكافحة التصحر",
        studyEntity: "جهة دراسة عامة",
        type: "مبادرات | الإنشاء والتنفيذ",
      },
    ],
  },
  en: {
    1: [
      {
        id: uuidv4(),
        name: "Development of the Seventh and Eighth National Park (Group Two - Phase Two)",
        status: "late",
        percentage: 0.0,
        consultant: "Arab Creativity Office for Engineering Consultations",
        contractor: "Palm Shadow Contracting Company is a one-person company.",
        department: "General Administration of National Parks",
        owner: "National Center for Vegetation Cover Development and Combating Desertification",
        studyEntity: "General Study Authority",
        type: "Initiatives | Creation and implementation",
      },
      {
        id: uuidv4(),
        name: "Establishment of the Sixth Park (Al-Sabkha) (Group One - Phase Two)",
        status: "onSchedule",
        percentage: 0.0,
        consultant: "Arab Creativity Office for Engineering Consultations",
        contractor: "Palm Shadow Contracting Company is a one-person company.",
        department: "General Administration of National Parks",
        owner: "National Center for Vegetation Cover Development and Combating Desertification",
        studyEntity: "General Study Authority",
        type: "Initiatives | Creation and implementation",
      },
      {
        id: uuidv4(),
        name: "Restoration and Rehabilitation of Al-Ahsa National Park in Al-Ahsa Governorate, Eastern Region",
        status: "late",
        percentage: 0.0,
        consultant: "Arab Creativity Office for Engineering Consultations",
        contractor: "Palm Shadow Contracting Company is a one-person company.",
        department: "General Administration of National Parks",
        owner: "National Center for Vegetation Cover Development and Combating Desertification",
        studyEntity: "General Study Authority",
        type: "Initiatives | Creation and implementation",
      },
      {
        id: uuidv4(),
        name: "Project for Afforestation of Al-Ani Wild Park in Wadi Hali, Al-Qunfudhah Governorate - Phase One",
        status: "onSchedule",
        percentage: 61.72,
        consultant: "Arab Creativity Office for Engineering Consultations",
        contractor: "Palm Shadow Contracting Company is a one-person company.",
        department: "General Administration of National Parks",
        owner: "National Center for Vegetation Cover Development and Combating Desertification",
        studyEntity: "General Study Authority",
        type: "Initiatives | Creation and implementation",
      },
      {
        id: uuidv4(),
        name: "Design of the Ninth and Tenth National Park (Group Two - Phase Two)",
        status: "stumbling",
        percentage: 20.0,
        consultant: "Arab Creativity Office for Engineering Consultations",
        contractor: "Palm Shadow Contracting Company is a one-person company.",
        department: "General Administration of National Parks",
        owner: "National Center for Vegetation Cover Development and Combating Desertification",
        studyEntity: "General Study Authority",
        type: "Initiatives | Creation and implementation",
      },
      {
        id: uuidv4(),
        name: "Development of the Ninth and Tenth National Park (Group Two - Phase Two)",
        status: "early",
        percentage: 5.0,
        consultant: "Arab Creativity Office for Engineering Consultations",
        contractor: "Palm Shadow Contracting Company is a one-person company.",
        department: "General Administration of National Parks",
        owner: "National Center for Vegetation Cover Development and Combating Desertification",
        studyEntity: "General Study Authority",
        type: "Initiatives | Creation and implementation",
      },
    ],
    2: [
      {
        id: uuidv4(),
        name: "Development of the Seventh and Eighth National Park (Group Two - Phase Two)",
        status: "late",
        percentage: 0.0,
        consultant: "Arab Creativity Office for Engineering Consultations",
        contractor: "Palm Shadow Contracting Company is a one-person company.",
        department: "General Administration of National Parks",
        owner: "National Center for Vegetation Cover Development and Combating Desertification",
        studyEntity: "General Study Authority",
        type: "Initiatives | Creation and implementation",
      },
      {
        id: uuidv4(),
        name: "Establishment of the Sixth Park (Al-Sabkha) (Group One - Phase Two)",
        status: "onSchedule",
        percentage: 0.0,
        consultant: "Arab Creativity Office for Engineering Consultations",
        contractor: "Palm Shadow Contracting Company is a one-person company.",
        department: "General Administration of National Parks",
        owner: "National Center for Vegetation Cover Development and Combating Desertification",
        studyEntity: "General Study Authority",
        type: "Initiatives | Creation and implementation",
      },
      {
        id: uuidv4(),
        name: "Restoration and Rehabilitation of Al-Ahsa National Park in Al-Ahsa Governorate, Eastern Region",
        status: "late",
        percentage: 0.0,
        consultant: "Arab Creativity Office for Engineering Consultations",
        contractor: "Palm Shadow Contracting Company is a one-person company.",
        department: "General Administration of National Parks",
        owner: "National Center for Vegetation Cover Development and Combating Desertification",
        studyEntity: "General Study Authority",
        type: "Initiatives | Creation and implementation",
      },
      {
        id: uuidv4(),
        name: "Project for Afforestation of Al-Ani Wild Park in Wadi Hali, Al-Qunfudhah Governorate - Phase One",
        status: "onSchedule",
        percentage: 61.72,
        consultant: "Arab Creativity Office for Engineering Consultations",
        contractor: "Palm Shadow Contracting Company is a one-person company.",
        department: "General Administration of National Parks",
        owner: "National Center for Vegetation Cover Development and Combating Desertification",
        studyEntity: "General Study Authority",
        type: "Initiatives | Creation and implementation",
      },
      {
        id: uuidv4(),
        name: "Design of the Ninth and Tenth National Park (Group Two - Phase Two)",
        status: "stumbling",
        percentage: 20.0,
        consultant: "Arab Creativity Office for Engineering Consultations",
        contractor: "Palm Shadow Contracting Company is a one-person company.",
        department: "General Administration of National Parks",
        owner: "National Center for Vegetation Cover Development and Combating Desertification",
        studyEntity: "General Study Authority",
        type: "Initiatives | Creation and implementation",
      },
      {
        id: uuidv4(),
        name: "Development of the Ninth and Tenth National Park (Group Two - Phase Two)",
        status: "early",
        percentage: 5.0,
        consultant: "Arab Creativity Office for Engineering Consultations",
        contractor: "Palm Shadow Contracting Company is a one-person company.",
        department: "General Administration of National Parks",
        owner: "National Center for Vegetation Cover Development and Combating Desertification",
        studyEntity: "General Study Authority",
        type: "Initiatives | Creation and implementation",
      },
    ],
  },
};
